name = "ASCII"
defaultTargets = ["ASCII"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.9.0"

[[lean_lib]]
name = "ASCII"
precompileModules = true
